### ISSUE TITLE
Design Backend Structure

### ISSUE THREAD

**Issue by JiahuiChen99** [mokumoku-lovers/moku-moku-users#1]
Design the back-end structure for the language learning platorm.

@mokumoku-lovers/moku-back We're considering using a microservices approach instead the more traditional, monolithic approach

### User API v0.1

- [x] User Domain Definition (#3)
- [x] Get User (#8)
- [x] Add User (#4)
- [x] Update User (#5)
- [x] Patch User (#6)
- [x] Delete User (#7)

**Comment by nicolewert** [comment]
![Microservices(1)](https://user-images.githubusercontent.com/31603986/124760201-76a5bc80-df6b-11eb-914f-8d77df3192be.png)

**Comment by JiahuiChen99** [comment]
- [ ] User Domain Definition (#3)
- [ ] Add User (#4)
- [ ] Update User (#5)
- [ ] Patch User (#6)
- [ ] Delete User (#7)
