### ISSUE TITLE
Update points

### ISSUE THREAD

**Issue by JiahuiChen99** [mokumoku-lovers/moku-moku-users#34]
Update the points that the user has accumulated

**Comment by xyzhg** [comment]
Question:
Is this endpoint necessary? Why not just use PATCH? Let's discuss this evening~

**Comment by JiahuiChen99** [comment]
The Request Type will be PATCH as you said. I guess it sound better the fact that it's an endpoint to update users' points 👀

**Comment by xyzhg** [comment]
Got it!
