### ISSUE TITLE
Requests from front-end are blocked by CORS policy

### ISSUE THREAD

**Issue by Yin-Lynn-Htun** [mokumoku-lovers/moku-moku-users#44]
![image](https://user-images.githubusercontent.com/37770349/132511075-4f6dd64a-edd5-46d9-b777-92fe90f57ebc.png)

**Comment by Yin-Lynn-Htun** [comment]
The newer version still doesn't work.

**Comment by JiahuiChen99** [comment]
We'll try to fix this as soon as possible 😬

**Comment by JiahuiChen99** [comment]
Now it's definitely solved as we reviewed yesterday! 🎉
