### ISSUE TITLE
Update User

### ISSUE THREAD

**Issue by JiahuiChen99** [mokumoku-lovers/moku-moku-users#5]
Update user endpoint

**Comment by xyzhg** [comment]
// From Jiahui

Created Create User endpoint, before saving the user to the database, it performs some email and password validation.
The connection to the DB is yet to be implemented in the #13 issue.
We'll discuss and address this in 21/07/2021 @mokumoku-lovers/moku-back meeting

You can view, comment on, or merge this pull request online at:
  https://github.com/mokumoku-lovers/moku-moku-backend/pull/20

Commit Summary
#4 feat: User creation in User controller
#4 feat: Call User service to create a new user
#4 feat: User creation middleware
#4 feat: Service calls DTO save
#4 feat: CreateUser endpoint routing
#4 feat: Return created user to client
File Changes
M app/routing.go (1)
M controllers/users/UserController.go (22)
M services/UserService.go (19)
Patch Links:
https://github.com/mokumoku-lovers/moku-moku-backend/pull/20.patch
https://github.com/mokumoku-lovers/moku-moku-backend/pull/20.diff

**Comment by xyzhg** [comment]
Skipped.
